ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "aiProfile" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "aiAutopublish" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "variants" JSONB;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "source" TEXT NOT NULL DEFAULT 'manual';
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "aiText" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "aiImage" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "logoUrl" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "phone" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "brandImages" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "logoLightUrl" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "color2" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "color3" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "fontHeading" TEXT NOT NULL DEFAULT 'montserrat';
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "fontBody" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "brandVoice" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "brandBookUrl" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "hashtags" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "template" TEXT NOT NULL DEFAULT 'auto';
CREATE TABLE IF NOT EXISTS "Template" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "businessId" TEXT NOT NULL REFERENCES "Business"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  "name" TEXT NOT NULL,
  "spec" JSONB NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS "Template_businessId_idx" ON "Template"("businessId");
ALTER TABLE "Template" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "Template" FROM anon, authenticated;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "study" JSONB;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "studyInput" JSONB;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "studyAt" TIMESTAMP(3);
CREATE TABLE IF NOT EXISTS "SeoReport" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "businessId" TEXT NOT NULL REFERENCES "Business"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  "kind" TEXT NOT NULL,
  "data" JSONB NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS "SeoReport_businessId_kind_createdAt_idx" ON "SeoReport"("businessId", "kind", "createdAt");
ALTER TABLE "SeoReport" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "SeoReport" FROM anon, authenticated;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "seoLocationCode" INTEGER;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "seoLocationName" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "seoLanguage" TEXT NOT NULL DEFAULT 'es';
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "seoKeywords" JSONB;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "seoDaily" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "seoLocations" JSONB;
